version: 0.2

# Environment variables that should be set in CodeBuild project:
# - ECR_REPOSITORY_URI: The full URI of your ECR repository
# - AWS_DEFAULT_REGION: AWS region (e.g., us-east-1)
# - AWS_ACCOUNT_ID: Your AWS account ID
# - CONTAINER_NAME: Name for the container in task definition (default: fastapi-container)

env:
  variables:
    CONTAINER_NAME: fastapi-container

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Install phase started on `date`
      - echo Checking Docker version
      - docker --version
      - echo Checking AWS CLI version
      - aws --version

  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - echo Logging in to Amazon ECR...
      - echo ECR Repository URI is $ECR_REPOSITORY_URI
      - echo AWS Region is $AWS_DEFAULT_REGION
      - echo AWS Account ID is $AWS_ACCOUNT_ID
      - |
        if [ -z "$ECR_REPOSITORY_URI" ]; then
          echo "ERROR: ECR_REPOSITORY_URI environment variable is not set"
          exit 1
        fi
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Logged in to ECR successfully
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - echo Image tag will be $IMAGE_TAG
      - echo Commit ID is $CODEBUILD_RESOLVED_SOURCE_VERSION
      
  build:
    commands:
      - echo Build phase started on `date`
      - echo Building Docker image...
      - echo "Building image: $ECR_REPOSITORY_URI:$IMAGE_TAG"
      - docker build -t $ECR_REPOSITORY_URI:$IMAGE_TAG .
      - echo "Tagging image as latest: $ECR_REPOSITORY_URI:latest"
      - docker tag $ECR_REPOSITORY_URI:$IMAGE_TAG $ECR_REPOSITORY_URI:latest
      - echo Docker build completed successfully
      
  post_build:
    commands:
      - echo Post-build phase started on `date`
      - echo Pushing Docker images to ECR...
      - echo "Pushing image with tag: $IMAGE_TAG"
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - echo "Pushing image with tag: latest"
      - docker push $ECR_REPOSITORY_URI:latest
      - echo Docker images pushed successfully
      - echo Creating imagedefinitions.json for ECS deployment...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $ECR_REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Contents of imagedefinitions.json:
      - cat imagedefinitions.json
      - echo Build completed successfully on `date`
      
artifacts:
  files:
    - imagedefinitions.json
  name: FastAPIBuildArtifact

# Optional: Store build logs in CloudWatch
reports:
  docker-build-report:
    files:
      - '**/*'
    name: DockerBuildReport
    file-format: 'CUCUMBERJSON'

# Cache Docker layers for faster builds (optional)
cache:
  paths:
    - '/root/.docker/**/*'